services:
  sonar-lts:
    image: sonarqube:lts
    hostname: sonar-lts
    ports:
      - 9500:9000
    networks:
      - sonarnet
  jenkins-lts:
    build:
      context: ../
      dockerfile: docker-test/Dockerfile
    ports:
      - 8888:8080
      - 50000:50000
    volumes:
      - jenkins-lts-data:/var/jenkins_home
    networks:
      - sonarnet

volumes:
  jenkins-lts-data:

networks:
  sonarnet:
